import type { NextPage } from "next"
import Head from "next/head"
import { useRouter } from "next/router"
import {
  Navbar,
  Button,
  Link,
  Text,
  Card,
  Spacer,
  Radio,
  useTheme,
	Image,
} from "@nextui-org/react"
import styles from "../styles/Home.module.scss"

const Home: NextPage = () => {
	return (
    <div className={styles.container}>
      <Head>
        <title>Foodverse | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/foodverselogo.png" />
      </Head>
      <main className={styles.main}>
        <>
          <Navbar isBordered={true} variant="sticky">
            <Navbar.Brand>
              <Image
                width={64}
                height={64}
                src="/foodverselogo.png"
                alt="Default Image"
                objectFit="cover"
              />
            </Navbar.Brand>
            <Navbar.Content
              activeColor={"primary"}
              hideIn="xs"
              variant={"underline"}
            >
              <Navbar.Link href="#">Features</Navbar.Link>
              <Navbar.Link isActive href="#">
                Customers
              </Navbar.Link>
              <Navbar.Link href="#">Pricing</Navbar.Link>
              <Navbar.Link href="#">Company</Navbar.Link>
            </Navbar.Content>
            <Navbar.Content>
              <Navbar.Link color="inherit" href="#">
                Login
              </Navbar.Link>
              <Navbar.Item>
                <Button auto flat as={Link} color={"primary"} href="#">
                  Sign Up
                </Button>
              </Navbar.Item>
            </Navbar.Content>
          </Navbar>
        </>
      </main>
    </div>
  )
}

export default Home